### ISSUE TITLE
Teach me this?

### ISSUE THREAD

**Issue by dphilla** [bretfunk/code-splitting#1]
I'm going to let you figure it out, and then you can patiently explain it to me. Sound fun? Cool.

**Comment by bretfunk** [comment]
I am doing this super great tutorial on udemy called junior to senior
developer and today I learned about code splitting (only downloading
frontend code when needed instead of bundling and downloading all at once).
The tutorial is more frontend imo but I have learned a ton and it is only
$11.

Code splitting isn’t that big of a deal unless you are Amazon.com so I
wouldn’t worry about it. React already just renders only what has changed
anyway so we don’t even use it at my job.

https://www.udemy.com/the-complete-junior-to-senior-web-developer-roadmap/
